export const FETCH_LECTURES_ATTEMPTED = "FETCH_LECTURES_ATTEMPTED";
export const FETCH_LECTURES_SUCCESSFUL = "FETCH_LECTURES_SUCCESSFUL";
export const FETCH_LECTURES_FAILED = "FETCH_LECTURES_FAILED"; 
