export const FETCH_PROJECTS_ATTEMPTED = "FETCH_PROJECTS_ATTEMPTED";
export const FETCH_PROJECTS_SUCCESSFUL = "FETCH_PROJECTS_SUCCESSFUL";
export const FETCH_PROJECTS_FAILED = "FETCH_PROJECTS_FAILED"; 

export const  FETCH_PROJECT_ATTEMPTED = "FETCH_PROJECT_ATTEMPTED";
export const  FETCH_PROJECT_SUCCESSFUL = "FETCH_PROJECT_SUCCESSFUL";
export const  FETCH_PROJECT_FAILED = "FETCH_PROJECT_FAILED"; 