export const FETCH_BLOGS_ATTEMPT = "FETCH_BLOGS_ATTEMPT";
export const FETCH_BLOGS_SUCCESS = "FETCH_BLOGS_SUCCESS"; 
export const FETCH_BLOGS_FAILED = "FETCH_BLOGS_FAILED"; 

export const POST_BLOG_ATTEMPT = "POST_BLOG_ATTEMPT";
export const POST_BLOG_SUCCESS = "POST_BLOG_SUCCESS";
export const POST_BLOG_FAILED = "POST_BLOG_FAILED";

export const EDIT_BLOG_ATTEMPT = "EDIT_BLOG_ATTEMPT";
export const EDIT_BLOG_SUCCESS = "EDIT_BLOG_SUCCESS"; 
export const EDIT_BLOG_FAILED = "EDIT_BLOG_FAILED"; 

export const DELETE_BLOG_ATTEMPT = "DELETE_BLOG_ATTEMPT";
export const DELETE_BLOG_SUCCESS = "DELETE_BLOG_SUCCESS"; 
export const DELETE_BLOG_FAILED = "DELETE_BLOG_FAILED"; 